### ISSUE TITLE
Create track.

### ISSUE THREAD

**Issue by MarcAbonce** [erikiado/NotMarioKart#1]
TODO:
- [x] Straight line track
- [x] Rainbow texture
- [x] Curves
- [x] Infinite loop

**Comment by BenjaVR** [comment]
Infinite track (circle/oval).

**Comment by MarcAbonce** [comment]
d0754790162d90307bcd97836c6d4130f34b7a68 changes track so it's drawn as a (Centripetal Catmull–Rom spline)[https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline].

For now the track is still hardcoded, for the next delivery we can change that by either adding levels or by random generation.
