### ISSUE TITLE
New project structure

### ISSUE THREAD

**Issue by BenjaVR** [erikiado/NotMarioKart#13]
Guys, I changed the structure of the project to use some folders and build the source files etc. Could you take a look at the other branch ([project-structure](https://github.com/erikiado/NotMarioKart/tree/project-structure)) to see if you understand/like it? If you don't like it we don't have to use it this way, but to me it seems more convenient.

Thoughts?

PS: Don't forget to take a look in the source files, some things are change, although not a lot.

**Comment by MarcAbonce** [comment]
Yeah.

**Comment by BenjaVR** [comment]
Great! Merging it to master
